const CHAT_REQUEST = 'CHAT_REQUEST';
const CHAT_REQUEST_APPROVE = 'CHAT_REQUEST_APPROVE';
const ADD_NEW_USER = 'ADD_NEW_USER';
const ADD_REQ_ACCEPTED = 'ADD_REQ_ACCEPTED';
const NEW_USER_ADDED = 'NEW_USER_ADDED';
const CHAT_REQ_TO_CLIENT = 'CHAT_REQ_TO_CLIENT';
const CHAT_REQ_APPROVE_TO_CLIENT = 'CHAT_REQ_APPROVE_TO_CLIENT';
const SEND_MESSAGE_TO = 'SEND_MESSAGE_TO';
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
const CHAT_REQ_ACCEPTED = 'CHAT_REQ_ACCEPTED';
const CHAT_REQUEST_APPROVED = 'CHAT_REQUEST_APPROVED';
const CHAT_REQUEST_DENIED = 'CHAT_REQUEST_DENIED';
const CHAT_REQ_REJECTED = 'CHAT_REQ_REJECTED';

module.exports = {
    ADD_NEW_USER,
    CHAT_REQUEST_APPROVE,
    CHAT_REQUEST,
    ADD_REQ_ACCEPTED,
    NEW_USER_ADDED,
    CHAT_REQ_TO_CLIENT,
    CHAT_REQ_APPROVE_TO_CLIENT,
    SEND_MESSAGE_TO,
    MESSAGE_RECEIVED,
    CHAT_REQ_ACCEPTED,
    CHAT_REQ_REJECTED,
    CHAT_REQUEST_APPROVED,
    CHAT_REQUEST_DENIED
};