 const SOCKET_EVENT_NEW_CHAT_REQUEST = 'SOCKET_EVENT_NEW_CHAT_REQUEST';
 const SOCKET_EVENT_CHAT_REQUEST_APPROVED = 'SOCKET_EVENT_CHAT_REQUEST_APPROVED';
 const SOCKET_EVENT_ADD_NEW_USER = 'SOCKET_EVENT_ADD_NEW_USER';
 const SOCKET_EVENT_NEW_USER_ADDED = 'SOCKET_EVENT_NEW_USER_ADDED';
 const SOCKET_EVENT_I_AM_ADDED = 'SOCKET_EVENT_YOU_ARE_ADDED';
 const SOCKET_EVENT_I_HAVE_CHAT_REQUEST = 'SOCKET_EVENT_I_HAVE_CHAT_REQUEST';
 const SOCKET_EVENT_MY_CHAT_REQUEST_APPROVED = 'SOCKET_EVENT_MY_CHAT_REQUEST_APPROVED';
 const SOCKET_EVENT_SEND_MESSAGE_TO = 'SOCKET_EVENT_SEND_MESSAGE_TO';
 const SOCKET_EVENT_MESSAGE_RECEIVED_FROM = 'SOCKET_EVENT_MESSAGE_RECEIVED_FROM';
 const SOCKET_EVENT_EXISTING_USER_DISCONNECTED = 'SOCKET_EVENT_EXISTING_USER_DISCONNECTED';


module.exports = {
    SOCKET_EVENT_NEW_CHAT_REQUEST,
    SOCKET_EVENT_CHAT_REQUEST_APPROVED,
    SOCKET_EVENT_ADD_NEW_USER,
    SOCKET_EVENT_NEW_USER_ADDED,
    SOCKET_EVENT_I_AM_ADDED,
    SOCKET_EVENT_I_HAVE_CHAT_REQUEST,
    SOCKET_EVENT_MY_CHAT_REQUEST_APPROVED,
    SOCKET_EVENT_SEND_MESSAGE_TO,
    SOCKET_EVENT_MESSAGE_RECEIVED_FROM,
    SOCKET_EVENT_EXISTING_USER_DISCONNECTED
};