export const USER_JOIN_REQ_ACCEPTED = 'USER_JOIN_REQ_ACCEPTED';
export const NEW_USER_JOINED = 'NEW_USER_JOINED';
export const SEND_CHAT_REQUEST = 'SEND_CHAT_REQUEST';
export const NEW_CHAT_REQUEST = 'NEW_CHAT_REQUEST';
export const SEND_MESSAGE_ACTION = 'SEND_MESSAGE_ACTION';
export const MESSAGE_RECIEVED_ACTION = 'MESSAGE_RECIEVED_ACTION';
export const LOAD_OLD_MESSAGES = 'LOAD_OLD_MESSAGES';