export const USER_JOIN_REQ_ACCEPTED = 'USER_JOIN_REQ_ACCEPTED';
export const NEW_USER_JOINED = 'NEW_USER_JOINED';
export const SEND_CHAT_REQUEST = 'SEND_CHAT_REQUEST';
export const APPROVED_CHAT_REQUEST = 'APPROVED_CHAT_REQUEST';
export const REJECTED_CHAT_REQUEST = 'REJECTED_CHAT_REQUEST';
export const NEW_CHAT_REQUEST = 'NEW_CHAT_REQUEST';
export const SEND_MESSAGE_ACTION = 'SEND_MESSAGE_ACTION';
export const MESSAGE_RECIEVED_ACTION = 'MESSAGE_RECIEVED_ACTION';
export const LOAD_OLD_MESSAGES = 'LOAD_OLD_MESSAGES';

export const CHAT_REQUEST_APPROVAL_RECIEVED = 'CHAT_REQUEST_APPROVAL_RECIEVED';
export const CHAT_REQUEST_DENIAL_RECIEVED = 'CHAT_REQUEST_DENIAL_RECIEVED';